config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  root :to => 'events#index'
  root :to => 'posts#index'


  devise_for :users

  resources :users, only: [:show]

  resources :charges


  resources :events do 
    resources :participations, only: [:index, :new, :create, :show]
  end

  namespace :admin do
    root :to => 'admin#index'
    resources :users  
    resources :events
    resources :posts 

  end

end

app/controllers/participation_controller.rb
class ParticipationController < ApplicationController
    def index 
        @participants = Attendance.where(event_id: params[:event_id])
        puts @participants
        @event = Event.find(params[:event_id])
      end
      
      def new
        @event = Event.new
        
        ##to display amount on page
        @amount = Event.find(params[:event_id]).price
      end

      def create
        ##define amount by finding into Event object
        ##amount always in cent so *100!
        @amount = (Event.find(params[:event_id]).price) * 100
        
        customer = Stripe::Customer.create(
          :email => params[:stripeEmail],
          :source  => params[:stripeToken]
        )
      
        charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount      => @amount,
          :description => 'Rails Stripe customer',
          :currency    => 'usd'
        )
    
        ##create a new participation/attende
        @attendee = Attendance.new(
          stripe_customer_id: customer.id, 
          event_id: params[:event_id], 
          guest_id: current_user.id)
    
        ##if charge success, save participation.
        ##if participation success, redirection, otherwise retry
        if charge.save
          if @attendee.save
          flash[:success] = "Vous avez bien été débité de #{@amount / 100}€, et êtes bien inscrit à l'événement !"
          redirect_to event_path(params[:event_id])
          return 
          else 
            flash[:error] = "Une erreur s'est produite"
            redirect_to new_event_participation_path
          end
        else
        end
      
      ##error message
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_participation_path
      end
end

app/helpers/participation_helper.rb
module ParticipationHelper
end

app/views/participation/index.html.erb
<div class="container mt-2 mb-5">
<h2> Liste des participants </h2>
<a class="" href="<%= edit_event_path(@event.id) %>" role="button">Editer</a>
<a href="<%= event_path(@event.id)%>" data-confirm="Voulez-vous vraiment supprimer cet événément?" data-method="DELETE"><i class="fas fa-trash-alt"></i></a>
  <table class="table table-striped mt-4" style="background-color: #e3f2fd;">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Event Id</th>
        <th scope="col">Guest Id</th>
        <th scope="col">Email</th>
        <th scope="col">Titre Event</th>
      </tr>
    </thead>
    <tbody>
      <% @participants.each do |attendee| %>
        <tr>
          <th scope="row"><%= %></th>
          <td><%= attendee.event.id %></td>
          <td><%= attendee.guest.id %></td>
          <td><%= attendee.guest.email %></td>
          <td><%= attendee.event.title %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>